### PR TITLE
Filtering test output and gold strings 

### PR DESCRIPTION
**Pull request by tramhnt99**

### CODE REVIEW

**Comment by vaivaswatha** [comment]
@tramhnt99 
1. For CI to pickup the latest `Scilla_base`, https://github.com/Zilliqa/scilla-compiler/blob/master/.github/workflows/workflow.yml#L31 must be updated to new version `v3`. Similarly the LLVM build cache too.
2. There's a more serious issue though. https://github.com/Zilliqa/scilla/pull/1020 introduces a new Scilla construct that isn't handled in the compiler. That will cause build issues in the compiler. You will need to fix that. You don't need to support it, but just `fail "..."` will do, to get the builds running.

Let me know if you need help with either of these.

**Comment by vaivaswatha** [comment]
Thank you @tramhnt99 .

The filter function is repeated twice. It may be better to place it in `tests/codegen/utils/Utils.ml` and reuse the same code.

Also adding @anton-trunov as a reviewer to see if there's a better way to implement the filter itself. (reference: https://github.com/Zilliqa/scilla/pull/1029).

**Comment by vaivaswatha** [comment]
@tramhnt99 Anton has the following comment to start with: 

>perhaps we could start with adding a couple comments explaining what exactly those filters keep (or filter out)

We'll see if the filter can be improved. 

Thank you both @tramhnt99 and @anton-trunov

**Comment by tramhnt99** [comment]
> Thank you @tramhnt99 .
> 
> The filter function is repeated twice. It may be better to place it in `tests/codegen/utils/Utils.ml` and reuse the same code.
> 
> Also adding @anton-trunov as a reviewer to see if there's a better way to implement the filter itself. (reference: [Zilliqa/scilla#1029](https://github.com/Zilliqa/scilla/pull/1029)).

I can't seem to find a file `tests/codegen/utils/Utils.ml`. Should I create a new file?

**Comment by vaivaswatha** [comment]
> > Thank you @tramhnt99 .
> > The filter function is repeated twice. It may be better to place it in `tests/codegen/utils/Utils.ml` and reuse the same code.
> > Also adding @anton-trunov as a reviewer to see if there's a better way to implement the filter itself. (reference: [Zilliqa/scilla#1029](https://github.com/Zilliqa/scilla/pull/1029)).
> 
> I can't seem to find a file `tests/codegen/utils/Utils.ml`. Should I create a new file?

Yes. You may need to add a `dune` file for it too.

**Review by vaivaswatha — APPROVED** [review]

**Comment by vaivaswatha** [comment]
LGTM. We'll merge once @anton-trunov confirms on the filtering function.

**Comment by vaivaswatha** [comment]
@tramhnt99 
Can we not just call [`global_replace`](https://ocaml.org/api/Str.html) on a regexp on the input, replacing the matched regexp (which could be defined to be an OR of the two patterns we're looking for) with an empty string.

**Comment by tramhnt99** [comment]
> @tramhnt99
> Can we not just call [`global_replace`](https://ocaml.org/api/Str.html) on a regexp on the input, replacing the matched regexp (which could be defined to be an OR of the two patterns we're looking for) with an empty string.

Updated! The function is much shorter now.

**Comment by vaivaswatha** [comment]
Thank you @tramhnt99

**Pull request merged**
